"""Discovery record test vectors smoke test (Phase 1 hangover).

The Phase 1 discovery_record.py module shipped without dedicated
test vectors. The Phase 0 envelope vectors had valid + tampered
counterparts that any third-party verifier could load. This module
adds the equivalent for discovery records: verify the
``valid-discovery-record.json`` succeeds and the
``tampered-discovery-record.json`` fails at signature check.

The vectors are regenerated by ``_regen_vectors.py``; this test
asserts they stay coherent with the verifier.
"""

import pathlib
import sys
import unittest
from datetime import UTC, datetime

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

from discovery_record import (
    DiscoveryRecordError,
    from_json,
    verify_record,
)
from verify_envelope import EnvelopeVerificationError

_VECTOR_DIR = pathlib.Path(__file__).resolve().parent / "test-vectors"
_ISSUER_PEM = (_VECTOR_DIR / "dev-issuer-1.pub.pem").read_bytes()
_ISSUER_IDENTITY = "spiffe://mesh/cap-issuer-1"
_ISSUER_KID = "dev-issuer-kid-1"

# The vectors were minted with issued_at = 2026-04-14T12:00:00Z.
# Verify at 2026-04-14T12:05:00Z so the window is comfortably open.
_VERIFY_AT = datetime(2026, 4, 14, 12, 5, 0, tzinfo=UTC)


def _issuer_lookup(iss: str, kid: str) -> bytes:
    if (iss, kid) != (_ISSUER_IDENTITY, _ISSUER_KID):
        raise EnvelopeVerificationError(
            f"unknown issuer: iss={iss!r}, kid={kid!r}"
        )
    return _ISSUER_PEM


class ValidVectorTests(unittest.TestCase):
    def test_valid_vector_verifies_clean(self):
        blob = (_VECTOR_DIR / "valid-discovery-record.json").read_bytes()
        record = from_json(blob)
        # Should not raise.
        verify_record(
            record,
            issuer_lookup=_issuer_lookup,
            now=_VERIFY_AT,
        )


class TamperedVectorTests(unittest.TestCase):
    def test_tampered_vector_fails_signature_check(self):
        blob = (_VECTOR_DIR / "tampered-discovery-record.json").read_bytes()
        record = from_json(blob)
        with self.assertRaises((DiscoveryRecordError, EnvelopeVerificationError)):
            verify_record(
                record,
                issuer_lookup=_issuer_lookup,
                now=_VERIFY_AT,
            )

    def test_tampered_endpoints_differ_from_valid(self):
        valid = from_json((_VECTOR_DIR / "valid-discovery-record.json").read_bytes())
        tampered = from_json(
            (_VECTOR_DIR / "tampered-discovery-record.json").read_bytes()
        )
        # The signatures are identical (the attacker reused the
        # valid one) — but the endpoints set differs.
        self.assertEqual(valid.signature, tampered.signature)
        self.assertNotEqual(valid.endpoints, tampered.endpoints)


if __name__ == "__main__":
    unittest.main()
